[build]
  # Client dependencies install + build
  command = "npm install --prefix client && npm run build --prefix client"
  publish = "client/dist"       # Vite default build folder
  functions = "functions"

[build.environment]
  NODE_ENV = "development"      # DevDependencies install এর জন্য
  PORT = "3000"                 # Optional, mostly server use

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
